export type Example = {
  id: string;
  title: string;
  code: string;
  tags: string[];
};

export const EXAMPLES: Example[] = [
  {
    id: 'basic-promise-timeout',
    title: 'Promise + setTimeout(0)',
    tags: ['promise', 'timeout', 'micro-vs-macro'],
    code: [
      "console.log('start')",
      '',
      'setTimeout(() => {',
      "  console.log('setTimeout')",
      '})',
      '',
      'Promise.resolve().then(() => {',
      "  console.log('resolve')",
      '})',
      '',
      "console.log('end')",
    ].join('\n'),
  },
  {
    id: 'nested-then-order',
    title: 'Вложенные then идут в конец очереди',
    tags: ['promise', 'then', 'microtasks'],
    code: [
      "console.log('A')",
      'Promise.resolve().then(() => {',
      "  console.log('B')",
      "  Promise.resolve().then(() => console.log('C'))",
      '})',
      "console.log('D')",
    ].join('\n'),
  },
  {
    id: 'double-resolve',
    title: 'Два Promise.resolve() подряд',
    tags: ['promise', 'microtasks'],
    code: [
      "console.log('start')",
      'Promise.resolve().then(() => console.log(1))',
      'Promise.resolve().then(() => console.log(2))',
      "console.log('end')",
    ].join('\n'),
  },
  {
    id: 'promise-then-chain',
    title: 'Цепочка then (микротаски по шагам)',
    tags: ['promise', 'then', 'chain'],
    code: [
      "console.log('start')",
      'Promise.resolve(1)',
      '  .then((v) => {',
      '    console.log(v)',
      '    return v + 1',
      '  })',
      '  .then((v) => {',
      '    console.log(v)',
      '    return v + 1',
      '  })',
      '  .then((v) => console.log(v))',
      "console.log('end')",
    ].join('\n'),
  },
  {
    id: 'microtask-inside-microtask',
    title: 'queueMicrotask внутри then',
    tags: ['queueMicrotask', 'promise', 'microtasks'],
    code: [
      "console.log('A')",
      'Promise.resolve().then(() => {',
      "  console.log('B')",
      "  queueMicrotask(() => console.log('C'))",
      "  console.log('D')",
      '})',
      "console.log('E')",
    ].join('\n'),
  },
  {
    id: 'timeout-order-by-delay',
    title: 'Два таймера: delay=0 и delay=5',
    tags: ['timeout', 'macro'],
    code: [
      "console.log('start')",
      "setTimeout(() => console.log('T0'), 0)",
      "setTimeout(() => console.log('T5'), 5)",
      "console.log('end')",
    ].join('\n'),
  },
  {
    id: 'timeout-same-delay-fifo',
    title: 'Два таймера с одинаковым delay (FIFO)',
    tags: ['timeout', 'macro', 'fifo'],
    code: [
      "console.log('start')",
      "setTimeout(() => console.log('T1'), 0)",
      "setTimeout(() => console.log('T2'), 0)",
      "console.log('end')",
    ].join('\n'),
  },
  {
    id: 'promise-and-multiple-timeouts',
    title: 'Promise между таймерами',
    tags: ['promise', 'timeout', 'micro-vs-macro'],
    code: [
      "console.log('start')",
      "setTimeout(() => console.log('T1'), 0)",
      "Promise.resolve().then(() => console.log('P'))",
      "setTimeout(() => console.log('T2'), 0)",
      "console.log('end')",
    ].join('\n'),
  },
  {
    id: 'microtask-queues-before-timeout',
    title: 'Несколько microtask до macrotask',
    tags: ['promise', 'queueMicrotask', 'timeout'],
    code: [
      "console.log('start')",
      "setTimeout(() => console.log('timeout'), 0)",
      "queueMicrotask(() => console.log('micro1'))",
      "Promise.resolve().then(() => console.log('micro2'))",
      "console.log('end')",
    ].join('\n'),
  },
  {
    id: 'timeout-schedules-micro',
    title: 'Внутри таймера планируем microtask',
    tags: ['timeout', 'promise', 'microtasks'],
    code: [
      "console.log('start')",
      'setTimeout(() => {',
      "  console.log('T')",
      "  Promise.resolve().then(() => console.log('P'))",
      '}, 0)',
      "console.log('end')",
    ].join('\n'),
  },
  {
    id: 'micro-schedules-timeout',
    title: 'Внутри microtask планируем таймер',
    tags: ['promise', 'timeout'],
    code: [
      "console.log('start')",
      'Promise.resolve().then(() => {',
      "  console.log('P')",
      "  setTimeout(() => console.log('T'), 0)",
      '})',
      "console.log('end')",
    ].join('\n'),
  },
  {
    id: 'new-promise-executor-sync',
    title: 'new Promise: executor синхронный',
    tags: ['promise', 'new'],
    code: [
      "console.log('start')",
      'new Promise((resolve) => {',
      '  console.log(1)',
      '  resolve(2)',
      '}).then((v) => console.log(v))',
      "console.log('end')",
    ].join('\n'),
  },
  {
    id: 'new-promise-then-then',
    title: 'new Promise + цепочка then',
    tags: ['promise', 'new', 'then', 'chain'],
    code: [
      "console.log('A')",
      'new Promise((resolve) => resolve(1))',
      '  .then((v) => {',
      "    console.log('B')",
      '    return v + 1',
      '  })',
      '  .then((v) => console.log(v))',
      "console.log('C')",
    ].join('\n'),
  },
  {
    id: 'queueMicrotask-basic',
    title: 'queueMicrotask: базовый порядок',
    tags: ['queueMicrotask', 'microtasks'],
    code: [
      "console.log('start')",
      "queueMicrotask(() => console.log('micro'))",
      "console.log('end')",
    ].join('\n'),
  },
  {
    id: 'queueMicrotask-two',
    title: 'Два queueMicrotask подряд (FIFO)',
    tags: ['queueMicrotask', 'microtasks', 'fifo'],
    code: [
      "console.log('start')",
      "queueMicrotask(() => console.log(1))",
      "queueMicrotask(() => console.log(2))",
      "console.log('end')",
    ].join('\n'),
  },
  {
    id: 'mix-micro-enqueue-during-sync',
    title: 'Планирование microtasks в sync (порядок регистрации)',
    tags: ['promise', 'queueMicrotask'],
    code: [
      "console.log('start')",
      "queueMicrotask(() => console.log('q1'))",
      "Promise.resolve().then(() => console.log('p1'))",
      "queueMicrotask(() => console.log('q2'))",
      "Promise.resolve().then(() => console.log('p2'))",
      "console.log('end')",
    ].join('\n'),
  },
  {
    id: 'promise-then-schedules-then',
    title: 'then внутри then: добавляем новую microtask',
    tags: ['promise', 'microtasks'],
    code: [
      "console.log('start')",
      'Promise.resolve().then(() => {',
      "  console.log('A')",
      "  Promise.resolve().then(() => console.log('B'))",
      '})',
      "Promise.resolve().then(() => console.log('C'))",
      "console.log('end')",
    ].join('\n'),
  },
  {
    id: 'timeouts-and-micro-between',
    title: 'Таймеры + microtasks (классика)',
    tags: ['timeout', 'promise', 'micro-vs-macro'],
    code: [
      "console.log(1)",
      "setTimeout(() => console.log(2), 0)",
      'Promise.resolve().then(() => console.log(3))',
      "console.log(4)",
    ].join('\n'),
  },
  {
    id: 'timeout-default-delay',
    title: 'setTimeout без delay (по умолчанию 0)',
    tags: ['timeout'],
    code: [
      "console.log('start')",
      'setTimeout(() => {',
      "  console.log('T')",
      '})',
      "console.log('end')",
    ].join('\n'),
  },
];

